FROM live-build-debian
COPY Makefile /home/livebuilder/hoarder-live/Makefile
COPY includes /home/livebuilder/hoarder-live/includes
COPY config.mk /home/livebuilder/hoarder-live/config.mk
RUN make docker-init
USER root
RUN make clean
USER livebuilder
COPY keyrings/
RUN make config-nonfree
RUN make libre
RUN make custom
RUN make skel
RUN make permissive-user
RUN make packages
USER root
